# **O Peso das Palavras - Análise Exploratória**

| Análise exploratória

## **1. Carregamento de Arquivos**

In [1]:
import pandas as pd
import numpy as np
import matplotlib . pyplot as plt
import seaborn as sns

from google.colab import drive

drive.mount('/content/drive')

df_avaliacoes = pd.read_csv ("/content/drive/MyDrive/Banco_de_Dados_PII3_AWS/avaliacoes.csv")
df_clientes = pd.read_csv ("/content/drive/MyDrive/Banco_de_Dados_PII3_AWS/clientes.csv")
df_geolocalizacao = pd.read_csv ("/content/drive/MyDrive/Banco_de_Dados_PII3_AWS/geolocalizacao.csv")
df_itens_pedidos = pd.read_csv ("/content/drive/MyDrive/Banco_de_Dados_PII3_AWS/itens_pedidos.csv")
df_pagamentos = pd.read_csv ("/content/drive/MyDrive/Banco_de_Dados_PII3_AWS/pagamentos.csv")
df_pedidos = pd.read_csv ("/content/drive/MyDrive/Banco_de_Dados_PII3_AWS/pedidos.csv")
df_produtos = pd.read_csv ("/content/drive/MyDrive/Banco_de_Dados_PII3_AWS/produtos.csv")
df_vendedores = pd.read_csv ("/content/drive/MyDrive/Banco_de_Dados_PII3_AWS/vendedores.csv")
df_auxiliar = pd.read_csv ("/content/drive/MyDrive/Banco_de_Dados_PII3_AWS/tabela_auxiliar.csv")

Mounted at /content/drive

## **2. Inspeção básica de Qualidade**
- As tabelas avaliacoes, pedidos, produtos foram inspecionadas com: shape, dtypes, head, tail, isnull e duplicated.

In [2]:
tabelas = {
    "df_avaliacoes": df_avaliacoes,
    "df_pedidos": df_pedidos,
    "df_produtos": df_produtos,
    "df_clientes": df_clientes,
    "df_itens_pedidos": df_itens_pedidos,
    "df_vendedores": df_vendedores,
    "df_geolocalizacao": df_geolocalizacao,
    "df_pagamentos": df_pagamentos,
    "df_auxiliar": df_auxiliar
}

for nome, df in tabelas.items():
    print(f"\n{'='*50}")
    print(f"TABELA: {nome}")
    print(f"{'='*50}")

    # Dimensão
    print("\nSHAPE:")
    print(df.shape)

    # Tipos de dados
    print("\nTIPO DE DADOS:")
    print(df.dtypes)

    # Primeiras e últimas linhas
    print("\n---------- PRIMEIRAS LINHAS:")
    print(df.head())

    print("\n---------- ÚLTIMAS LINHAS:")
    print(df.tail())

    # Valores nulos
    print("\n---------- VALORES NULOS POR COLUNA:")
    print(df.isnull().sum())

    # Duplicados
    print("\n---------- QUANTIDADE DE DUPLICADOS:")
    print(df.duplicated().sum())

    # Valores únicos (limitado para não poluir)
    print("\n---------- VALORES ÚNICOS (ATÉ 5 POR COLUNA):")
    for col in df.columns:
        print(f"{col}: {df[col].nunique()} ÚNICOS | EXEMPLO: {df[col].dropna().unique()[:5]}")

==================================================
TABELA: df_avaliacoes
==================================================

SHAPE:
(99224, 7)

TIPO DE DADOS:
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

---------- PRIMEIRAS LINHAS:
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53

---------- ÚLTIMAS LINHAS:
                              review_id                          order_id  \
99219  574ed12dd733e5fa530cfd4bbf39d7c9  2a8c23fee101d4d5662fa670396eb8da
99220  f3897127253a9592a73be9bdfdf4ed7a  22ec9f0669f784db00fa86d035cf8602
99221  b3de70c89b1510c4cd3d0649fd302472  55d4004744368f5571d1f590031933e4
99222  1adeb9d84d72fe4e337617733eb85149  7725825d039fc1f0ceb7635e3f7d9206
99223  efe49f1d6f951dd88b51e6ccd4cc548f  90531360ecb1eec2a1fbb265a0db0508

       review_score review_comment_title  \
99219             5                  NaN
99220             5                  NaN
99221             5                  NaN
99222             4                  NaN
99223             1                  NaN

                                  review_comment_message review_creation_date  \
99219                                                NaN  2018-07-07 00:00:00
99220                                                NaN  2017-12-09 00:00:00
99221  Excelente mochila, entrega super rápida. Super...  2018-03-22 00:00:00
99222                                                NaN  2018-07-01 00:00:00
99223  meu produto chegou e ja tenho que devolver, po...  2017-07-03 00:00:00

      review_answer_timestamp
99219     2018-07-14 17:18:30
99220     2017-12-11 20:06:42
99221     2018-03-23 09:10:43
99222     2018-07-02 12:59:13
99223     2017-07-03 21:01:49

---------- VALORES NULOS POR COLUNA:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

---------- QUANTIDADE DE DUPLICADOS:
0

---------- VALORES ÚNICOS (ATÉ 5 POR COLUNA):
review_id: 98410 ÚNICOS | EXEMPLO: ['7bc2406110b926393aa56f80a40eba40' '80e641a11e56f04c1ad469d5645fdfde'
 '228ce5500dc1d8e020d8d1322874b6f0' 'e64fb393e7b32834bb789ff8bb30750e'
 'f7c4243c7fe1938f181bec41a392bdeb']
order_id: 98673 ÚNICOS | EXEMPLO: ['73fc7af87114b39712e6da79b0a377eb' 'a548910a1c6147796b98fdf73dbeba33'
 'f9e4b658b201a9f2ecdecbb34bed034b' '658677c97b385a9be170737859d3511b'
 '8e6bfb81e283fa7e4f11123a3fb894f1']
review_score: 5 ÚNICOS | EXEMPLO: [4 5 1 3 2]
review_comment_title: 4527 ÚNICOS | EXEMPLO: ['recomendo' 'Super recomendo' 'Não chegou meu produto ' 'Ótimo'
 'Muito bom.']
review_comment_message: 36159 ÚNICOS | EXEMPLO: ['Recebi bem antes do prazo estipulado.'
 'Parabéns lojas lannister adorei comprar pela Internet seguro e prático Parabéns a todos feliz Páscoa'
 'aparelho eficiente. no site a marca do aparelho esta impresso como 3desinfector e ao chegar esta com outro nome...atualizar com a marca correta uma vez que é o mesmo aparelho'
 'Mas um pouco ,travando...pelo valor ta Boa.\r\n'
 'Vendedor confiável, produto ok e entrega antes do prazo.']
review_creation_date: 636 ÚNICOS | EXEMPLO: ['2018-01-18 00:00:00' '2018-03-10 00:00:00' '2018-02-17 00:00:00'
 '2017-04-21 00:00:00' '2018-03-01 00:00:00']
review_answer_timestamp: 98248 ÚNICOS | EXEMPLO: ['2018-01-18 21:46:59' '2018-03-11 03:05:13' '2018-02-18 14:36:24'
 '2017-04-21 22:02:06' '2018-03-02 10:26:53']

==================================================
TABELA: df_pedidos
==================================================

SHAPE:
(99441, 8)

TIPO DE DADOS:
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

---------- PRIMEIRAS LINHAS:
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00

---------- ÚLTIMAS LINHAS:
                               order_id                       customer_id  \
99436  9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00
99437  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7
99438  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c
99439  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1
99440  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24

      order_status order_purchase_timestamp    order_approved_at  \
99436    delivered      2017-03-09 09:54:05  2017-03-09 09:54:05
99437    delivered      2018-02-06 12:58:58  2018-02-06 13:10:37
99438    delivered      2017-08-27 14:46:43  2017-08-27 15:04:16
99439    delivered      2018-01-08 21:28:27  2018-01-08 21:36:21
99440    delivered      2018-03-08 20:57:30  2018-03-09 11:20:28

      order_delivered_carrier_date order_delivered_customer_date  \
99436          2017-03-10 11:18:03           2017-03-17 15:08:01
99437          2018-02-07 23:22:42           2018-02-28 17:37:56
99438          2017-08-28 20:52:26           2017-09-21 11:24:17
99439          2018-01-12 15:35:03           2018-01-25 23:32:54
99440          2018-03-09 22:11:59           2018-03-16 13:08:30

      order_estimated_delivery_date
99436           2017-03-28 00:00:00
99437           2018-03-02 00:00:00
99438           2017-09-27 00:00:00
99439           2018-02-15 00:00:00
99440           2018-04-03 00:00:00

---------- VALORES NULOS POR COLUNA:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

---------- QUANTIDADE DE DUPLICADOS:
0

---------- VALORES ÚNICOS (ATÉ 5 POR COLUNA):
order_id: 99441 ÚNICOS | EXEMPLO: ['e481f51cbdc54678b7cc49136f2d6af7' '53cdb2fc8bc7dce0b6741e2150273451'
 '47770eb9100c2d0c44946d9cf07ec65d' '949d5b44dbf5de918fe9c16f97b45f8a'
 'ad21c59c0840e6cb83a9ceb5573f8159']
customer_id: 99441 ÚNICOS | EXEMPLO: ['9ef432eb6251297304e76186b10a928d' 'b0830fb4747a6c6d20dea0b8c802d7ef'
 '41ce2a54c0b03bf3443c3d931a367089' 'f88197465ea7920adcdbec7375364d82'
 '8ab97904e6daea8866dbdbc4fb7aad2c']
order_status: 8 ÚNICOS | EXEMPLO: ['delivered' 'invoiced' 'shipped' 'processing' 'unavailable']
order_purchase_timestamp: 98875 ÚNICOS | EXEMPLO: ['2017-10-02 10:56:33' '2018-07-24 20:41:37' '2018-08-08 08:38:49'
 '2017-11-18 19:28:06' '2018-02-13 21:18:39']
order_approved_at: 90733 ÚNICOS | EXEMPLO: ['2017-10-02 11:07:15' '2018-07-26 03:24:27' '2018-08-08 08:55:23'
 '2017-11-18 19:45:59' '2018-02-13 22:20:29']
order_delivered_carrier_date: 81018 ÚNICOS | EXEMPLO: ['2017-10-04 19:55:00' '2018-07-26 14:31:00' '2018-08-08 13:50:00'
 '2017-11-22 13:39:59' '2018-02-14 19:46:34']
order_delivered_customer_date: 95664 ÚNICOS | EXEMPLO: ['2017-10-10 21:25:13' '2018-08-07 15:27:45' '2018-08-17 18:06:29'
 '2017-12-02 00:28:42' '2018-02-16 18:17:02']
order_estimated_delivery_date: 459 ÚNICOS | EXEMPLO: ['2017-10-18 00:00:00' '2018-08-13 00:00:00' '2018-09-04 00:00:00'
 '2017-12-15 00:00:00' '2018-02-26 00:00:00']

==================================================
TABELA: df_produtos
==================================================

SHAPE:
(32951, 9)

TIPO DE DADOS:
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

---------- PRIMEIRAS LINHAS:
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0

---------- ÚLTIMAS LINHAS:
                             product_id              product_category_name  \
32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

       product_name_lenght  product_description_lenght  product_photos_qty  \
32946                 45.0                        67.0                 2.0
32947                 41.0                       971.0                 1.0
32948                 50.0                       799.0                 1.0
32949                 60.0                       156.0                 2.0
32950                 58.0                       309.0                 1.0

       product_weight_g  product_length_cm  product_height_cm  \
32946           12300.0               40.0               40.0
32947            1700.0               16.0               19.0
32948            1400.0               27.0                7.0
32949             700.0               31.0               13.0
32950            2083.0               12.0                2.0

       product_width_cm
32946              40.0
32947              16.0
32948              27.0
32949              20.0
32950               7.0

---------- VALORES NULOS POR COLUNA:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

---------- QUANTIDADE DE DUPLICADOS:
0

---------- VALORES ÚNICOS (ATÉ 5 POR COLUNA):
product_id: 32951 ÚNICOS | EXEMPLO: ['1e9e8ef04dbcff4541ed26657ea517e5' '3aa071139cb16b67ca9e5dea641aaa2f'
 '96bd76ec8810374ed1b65e291975717f' 'cef67bcfe19066a932b7673e239eb23d'
 '9dc1a7de274444849c219cff195d0b71']
product_category_name: 73 ÚNICOS | EXEMPLO: ['perfumaria' 'artes' 'esporte_lazer' 'bebes' 'utilidades_domesticas']
product_name_lenght: 66 ÚNICOS | EXEMPLO: [40. 44. 46. 27. 37.]
product_description_lenght: 2960 ÚNICOS | EXEMPLO: [287. 276. 250. 261. 402.]
product_photos_qty: 19 ÚNICOS | EXEMPLO: [1. 4. 2. 3. 5.]
product_weight_g: 2204 ÚNICOS | EXEMPLO: [ 225. 1000.  154.  371.  625.]
product_length_cm: 99 ÚNICOS | EXEMPLO: [16. 30. 18. 26. 20.]
product_height_cm: 102 ÚNICOS | EXEMPLO: [10. 18.  9.  4. 17.]
product_width_cm: 95 ÚNICOS | EXEMPLO: [14. 20. 15. 26. 13.]

==================================================
TABELA: df_clientes
==================================================

SHAPE:
(99441, 5)

TIPO DE DADOS:
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

---------- PRIMEIRAS LINHAS:
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP

---------- ÚLTIMAS LINHAS:
                            customer_id                customer_unique_id  \
99436  17ddf5dd5d51696bb3d7c6291687be6f  1a29b476fee25c95fbafc67c5ac95cf8
99437  e7b71a9017aa05c9a7fd292d714858e8  d52a67c98be1cf6a5c84435bd38d095d
99438  5e28dfe12db7fb50a4b2f691faecea5e  e9f50caf99f032f0bf3c55141f019d99
99439  56b18e2166679b8a959d72dd06da27f9  73c2643a0a458b49f58cea58833b192e
99440  274fa6071e5e17fe303b9748641082c8  84732c5050c01db9b23e19ba39899398

       customer_zip_code_prefix    customer_city customer_state
99436                      3937        sao paulo             SP
99437                      6764  taboao da serra             SP
99438                     60115        fortaleza             CE
99439                     92120           canoas             RS
99440                      6703            cotia             SP

---------- VALORES NULOS POR COLUNA:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

---------- QUANTIDADE DE DUPLICADOS:
0

---------- VALORES ÚNICOS (ATÉ 5 POR COLUNA):
customer_id: 99441 ÚNICOS | EXEMPLO: ['06b8999e2fba1a1fbc88172c00ba8bc7' '18955e83d337fd6b2def6b18a428ac77'
 '4e7b3e00288586ebd08712fdd0374a03' 'b2b6027bc5c5109e529d4dc6358b12c3'
 '4f2d8ab171c80ec8364f7c12e35b23ad']
customer_unique_id: 96096 ÚNICOS | EXEMPLO: ['861eff4711a542e4b93843c6dd7febb0' '290c77bc529b7ac935b93aa66c333dc3'
 '060e732b5b29e8181a18229c7b0b2b5e' '259dac757896d24d7702b9acbbff3f3c'
 '345ecd01c38d18a9036ed96c73b8d066']
customer_zip_code_prefix: 14994 ÚNICOS | EXEMPLO: [14409  9790  1151  8775 13056]
customer_city: 4119 ÚNICOS | EXEMPLO: ['franca' 'sao bernardo do campo' 'sao paulo' 'mogi das cruzes' 'campinas']
customer_state: 27 ÚNICOS | EXEMPLO: ['SP' 'SC' 'MG' 'PR' 'RJ']

==================================================
TABELA: df_itens_pedidos
==================================================

SHAPE:
(112650, 7)

TIPO DE DADOS:
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

---------- PRIMEIRAS LINHAS:
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14

---------- ÚLTIMAS LINHAS:
                                order_id  order_item_id  \
112645  fffc94f6ce00a00581880bf54a75a037              1
112646  fffcd46ef2263f404302a634eb57f7eb              1
112647  fffce4705a9662cd70adb13d4a31832d              1
112648  fffe18544ffabc95dfada21779c9644f              1
112649  fffe41c64501cc87c801fd61db3f6244              1

                              product_id                         seller_id  \
112645  4aa6014eceb682077f9dc4bffebc05b0  b8bc237ba3788b23da09c0f1f3a3288c
112646  32e07fd915822b0765e448c4dd74c828  f3c38ab652836d21de61fb8314b69182
112647  72a30483855e2eafc67aee5dc2560482  c3cfdc648177fdbbbb35635a37472c53
112648  9c422a519119dcad7575db5af1ba540e  2b3e4a2a3ea8e01938cabda2a3e5cc79
112649  350688d9dc1e75ff97be326363655e01  f7ccf836d21b2fb1de37564105216cc1

        shipping_limit_date   price  freight_value
112645  2018-05-02 04:11:01  299.99          43.41
112646  2018-07-20 04:31:48  350.00          36.53
112647  2017-10-30 17:14:25   99.90          16.95

## **3. Tratando tipo de Dados**
- Análise e mudança do tipo de dados.

##### Analisar Texto

In [3]:
def analisar_texto(df, coluna):
    print(f"\n{'='*50}")
    print(f"ANÁLISE DA COLUNA: {coluna}")
    print(f"{'='*50}")

    # Nulos e vazios
    nulos = df[coluna].isnull().sum()
    vazios = (df[coluna].str.strip() == "").sum()

    print(f"\nValores nulos: {nulos}")
    print(f"Valores vazios (string vazia): {vazios}")

    # Tamanho dos textos
    tamanhos = df[coluna].apply(len)

    print("\nEstatísticas de tamanho:")
    print(tamanhos.describe())

    #Textos curtos
    print("\nExemplos de textos muito curtos:")
    print(df[df[coluna].str.len() < 5][coluna].head(5))

    #Espaços extras
    com_espaco = df[df[coluna].str.startswith(" ") |
                    df[coluna].str.endswith(" ")]

    print(f"\nTextos com espaços extras: {len(com_espaco)}")

    #Maiúsculas
    print("\nExemplo de textos em MAIÚSCULO:")
    print(df[df[coluna].str.isupper() == True][coluna].head(5))

##### 3.1 Tratando tabela avaliações

In [5]:
df_avaliacoes_tratado = df_avaliacoes.copy()

df_avaliacoes_tratado["review_id"] = df_avaliacoes_tratado["review_id"].astype("str")
df_avaliacoes_tratado["order_id"] = df_avaliacoes_tratado["order_id"].astype("str")

df_avaliacoes_tratado["review_comment_title"] = df_avaliacoes_tratado["review_comment_title"].astype("str")
df_avaliacoes_tratado["review_comment_message"] = df_avaliacoes_tratado["review_comment_message"].astype("str")

df_avaliacoes_tratado["review_creation_date"] = pd.to_datetime(df_avaliacoes_tratado["review_creation_date"])
df_avaliacoes_tratado["review_answer_timestamp"] = pd.to_datetime(df_avaliacoes_tratado["review_answer_timestamp"])

df_avaliacoes_tratado.dtypes

review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

##### 3.2 Tratamento da tabela pedidos

In [7]:
df_pedidos_tratado = df_pedidos.copy()

df_pedidos_tratado["customer_id"] = df_pedidos_tratado["customer_id"].astype("str")
df_pedidos_tratado["order_id"] = df_pedidos_tratado["order_id"].astype("str")

df_pedidos_tratado["order_status"] = df_pedidos_tratado["order_status"].astype("category")

df_pedidos_tratado["order_purchase_timestamp"] = pd.to_datetime(df_pedidos_tratado["order_purchase_timestamp"])
df_pedidos_tratado["order_approved_at"] = pd.to_datetime(df_pedidos_tratado["order_approved_at"])
df_pedidos_tratado["order_delivered_carrier_date"] = pd.to_datetime(df_pedidos_tratado["order_delivered_carrier_date"])
df_pedidos_tratado["order_delivered_customer_date"] = pd.to_datetime(df_pedidos_tratado["order_delivered_customer_date"])
df_pedidos_tratado["order_estimated_delivery_date"] = pd.to_datetime(df_pedidos_tratado["order_estimated_delivery_date"])

df_pedidos_tratado.dtypes

order_id                                 object
customer_id                              object
order_status                           category
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

##### 3.3 Tratamento da Tabela Produtos

In [8]:
df_produtos_tratado = df_produtos.copy()

df_produtos_tratado["product_id"] = df_produtos_tratado["product_id"].astype("str")

df_produtos_tratado["product_category_name"] = df_produtos_tratado["product_category_name"].astype("str")
df_produtos_tratado["product_name_lenght"] = df_produtos_tratado["product_name_lenght"].astype("Int64")

df_produtos_tratado["product_photos_qty"] = df_produtos_tratado["product_photos_qty"].astype("float64")
df_produtos_tratado["product_weight_g"] = df_produtos_tratado["product_weight_g"].astype("float64")
df_produtos_tratado["product_length_cm"] = df_produtos_tratado["product_length_cm"].astype("float64")
df_produtos_tratado["product_height_cm"] = df_produtos_tratado["product_height_cm"].astype("float64")
df_produtos_tratado["product_width_cm"] = df_produtos_tratado["product_width_cm"].astype("float64")

df_produtos_tratado.dtypes

product_id                     object
product_category_name          object
product_name_lenght             Int64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

## **4. Avaliações**

## C